baseURL = "/"
languageCode = "en-us"
theme = ["hugo-notice", "terminal"]
staticDir = "static"
enableRobotsTXT = "true"

[params]
  # source of content
  description = "bonedaddy's personal website and blog"
  contentTypeName = "blog"
  themeColor = "green"
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  showLastupdate = false
  enableGitInfo = true
  favicon = "favicon.ico"
  
[languages]
  [languages.en]
    languageName = "English"
    title = "Bonedaddy's Emporium"
    subtitle = "My Corner Of The Internet"
    owner = "bonedaddy"
    keywords = "blog personal github technology docker blockchain"
    menuMore = "Show More"
    readMore = "Read More"
    readOtherPosts = "Read Other Posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    [languages.en.params.logo]
      logoText = "Home"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        Name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        Name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "resume"
        Name = "Resume"
        url = "/resume"
      [[languages.en.menu.main]]
        identifier = "random"
        Name = "Random"
        url = "/Random"