baseURL = "/"
languageCode = "en-us"
theme = ["hugo-notice", "terminal"]
staticDir = "static"

[params]
  # source of content
  contentTypeName = "blog"
  themeColor = "green"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  showLastupdate = false
  enableGitInfo = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Bonedaddy's Emporium"
    subtitle = "My Corner Of The Internet"
    owner = "bonedaddy"
    keywords = "blog personal github technology"
    menuMore = "Show More"
    readMore = "Read More"
    readOtherPosts = "Read Other Posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    [languages.en.params.logo]
      logoText = "BDE"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        Name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        Name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "tests"
        Name = "Tests"
        url = "/tests"